spring:
  security:
    oauth2:
      client:
        registration:
          google:
            client-name: google
            client-id: ${GOOGLE_CLIENT_ID}
            client-secret: ${GOOGLE_CLIENT_SECRET}
            redirect-uri: /login/oauth2/code/google
#            authorization-grant-type: authorization_code
            scope:
              - email
              - profile
